### ISSUE TITLE
import fails with ImportError on "import version"

### ISSUE THREAD

**Issue by fmailhot** [cournape/talkbox#1]
First time using github...sorry if I'm doing this wrong...
# import scikits.talkbox

chokes and dies with an ImportError when scikits/talkbox/**init**.py tries to import a module named "version". Did you mean "from sys import version"? I commented the line out and things seem to work so far.

**Comment by cournape** [comment]
This is a bug - the version is talkbox version, not python version. A fix should be available in master in a few minutes

**Comment by cournape** [comment]
This should be fixed in version 0.2.4

**Comment by cournape** [comment]
Fixed
