### ISSUE TITLE
Minor query in theory

### ISSUE THREAD

**Issue by MerinS** [cournape/talkbox#5]
In this line of code,
https://github.com/cournape/talkbox/blob/master/scikits/talkbox/features/mfcc.py#L38

the parameter in the denominator is heights[i] which confuses me a bit, shouldn't it be a constant k, given how in general mfcc banks are in the range 0-k where k is any constant, generally 1

**Comment by cournape** [comment]
First, a disclaimer: I have not used this code for > 5 years, as I left academia a long time ago now , and my job involves very little signal processing :(

This is indeed not computing equal height filter bank, and looking at the comments, it sounds like I tried to follow the [auditory toolbox conventions](https://engineering.purdue.edu/~malcolm/interval/1998-010/). Looking at that code, the commend before the filterbank is:

> % We now want to combine FFT bins so that each filter has unit
> % weight, assuming a triangular weighting function.  First figure
> % out the height of the triangle, then we can figure out each 
> % frequencies contribution

I am not sure what are the tradeoff are between equal height and equal weight for MFCC calculation

**Comment by MerinS** [comment]
Thanks! It makes a lot more sense now.
